# WP 5 Seismology
## Exercises - Stress

The Exercises are taken from https://wolke.geophysik.uni-muenchen.de/s/FLn68bw4y4T9d3x?dir=undefined&path=%2F02_stress&openfile=1221306.

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3D import Axes3D

ModuleNotFoundError: No module named 'mpl_toolkits.mplot3D'

### 2.
Calculate the principal stresses (eigenvalues) and their directions. What is the direction of the largest stress (i.e., angels with the axes)? 

Hint: Best to do this with a Jupyter notebook. Try to plot the principle stress directions in 3D with arrows (or an ellipsoid). 

In [10]:
# Initizalize array
stress = np.array([[1/4, -5/4, (1/2)**(3/2)], [-5/4, 1/4, -(1/2)**(3/2)], [(1/2)**(3/2), -(1/2)**(3/2), 3/2]])
print(stress)

# Calculate eigenvalues and vectors
w, v = np.linalg.eig(stress)

print("The eigenvalues are {}".format(w))

print("The eigenvectors are \n{}".format(v))

[[ 0.25       -1.25        0.35355339]
 [-1.25        0.25       -0.35355339]
 [ 0.35355339 -0.35355339  1.5       ]]
The eigenvalues are [-1.  1.  2.]
The eigenvectors are 
[[ 7.07106781e-01  5.00000000e-01  5.00000000e-01]
 [ 7.07106781e-01 -5.00000000e-01 -5.00000000e-01]
 [ 9.38783434e-18 -7.07106781e-01  7.07106781e-01]]


In [ ]:
# Plot principle stress directions in 3D
fig = plt.figure()
ax = fig.add_subplot(111, project=)